package dev.foldcode.ide

import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.geometry.Rect
import androidx.compose.ui.unit.Density
import androidx.compose.ui.unit.Dp

internal data class WorkspaceLayoutMeasurements(
    val mode: LayoutMode,
    val shortLandscape: Boolean,
    val sidebarWidthValue: MutableWorkspaceValue<Float>,
    val sidebarMax: Dp,
    val panelWidth: Dp,
    val dexBrowserMax: Dp,
    val dexBrowserWidth: Dp,
    val drawerWidth: Dp,
    val baseDensity: Density,
    val dexDensity: Density,
    val dexScale: Float,
    val dexBrowserFile: ProjectFile?,
)

internal data class WorkspaceLayoutVariant(
    val desktopWorkspace: Boolean,
    val persistentSidebar: Boolean,
    val compactToolbar: Boolean,
    val workspaceDensity: Density,
    val uiScale: Float,
    val dexBrowserFile: ProjectFile?,
)

internal class WorkspaceLayoutBindings(
    val appearance: MutableWorkspaceValue<IdePreferences>,
    val showSettings: MutableWorkspaceValue<Boolean>,
    val files: MutableWorkspaceValue<Map<String, ProjectFile>>,
    val folders: () -> Set<String>,
    val projectTree: () -> List<ProjectTreeEntry>,
    val picoCMakeTargets: () -> List<String>,
    val projectName: () -> String,
    val projectKey: () -> String,
    val projectSources: () -> Map<String, String>,
    val openTabs: MutableWorkspaceValue<List<String>>,
    val activeFileName: MutableWorkspaceValue<String>,
    val splitEditorVisible: MutableWorkspaceValue<Boolean>,
    val secondaryActiveFileName: MutableWorkspaceValue<String>,
    val secondaryOpenTabs: MutableWorkspaceValue<List<String>>,
    val splitEditorRatio: MutableWorkspaceValue<Float>,
    val dexEditorZoom: MutableWorkspaceValue<Float>,
    val dexSecondaryEditorZoom: MutableWorkspaceValue<Float>,
    val destination: MutableWorkspaceValue<ActivityDestination>,
    val drawerOpen: MutableWorkspaceValue<Boolean>,
    val sidePanelVisible: MutableWorkspaceValue<Boolean>,
    val terminalVisible: MutableWorkspaceValue<Boolean>,
    val terminalHeightValue: MutableWorkspaceValue<Float>,
    val terminalWidthValue: MutableWorkspaceValue<Float>,
    val terminal: () -> String,
    val buildOutput: () -> String,
    val diagnosticsOutput: () -> String,
    val semanticCompletions: MutableWorkspaceValue<List<CompletionItem>>,
    val semanticDiagnostics: () -> List<CodeDiagnostic>,
    val building: () -> Boolean,
    val showBuildStatistics: () -> Boolean,
    val dexBrowserFileName: MutableWorkspaceValue<String>,
    val dexBrowserVisible: MutableWorkspaceValue<Boolean>,
    val dexBrowserWidthValue: MutableWorkspaceValue<Float>,
    val consoleActive: () -> Boolean,
    val terminalCommandRunning: () -> Boolean,
    val cleaningPicoBuild: () -> Boolean,
    val picotoolBusy: () -> Boolean,
    val gitState: () -> GitRepositoryState,
    val gitBusy: () -> Boolean,
    val gitNotice: () -> String?,
    val gitHubUsername: MutableWorkspaceValue<String>,
    val gitHubToken: MutableWorkspaceValue<String>,
    val dexWorkspaceActive: MutableWorkspaceValue<Boolean>,
    val desktopExplorerCommand: MutableWorkspaceValue<DesktopExplorerCommand?>,
    val editorDropBounds: MutableWorkspaceValue<Rect?>,
    val workspaceSurfaceBounds: MutableWorkspaceValue<Rect?>,
    val explorerDragPath: MutableWorkspaceValue<String?>,
    val explorerDragPosition: MutableWorkspaceValue<Offset?>,
    val editorDragSourceGroup: MutableWorkspaceValue<EditorGroup?>,
    val editorNavigation: () -> EditorNavigationRequest?,
    val terminalBeforeEditing: MutableWorkspaceValue<Boolean?>,
    val imeVisible: () -> Boolean,
    val debugSnapshot: () -> DebugSessionSnapshot,
    val toolbarOperationRunning: () -> Boolean,
    val buildStatisticsLabel: () -> String,
    val runDebugActions: () -> RunDebugActions,
    val debugToolbarActions: () -> DebugToolbarActions,
)

internal class WorkspaceLayoutActions(
    val toggleBuildStatistics: () -> Unit,
    val runCurrentProject: () -> Unit,
    val startDebugging: () -> Unit,
    val stopCurrentOperation: () -> Unit,
    val saveCurrent: () -> Unit,
    val closeFile: (String) -> Unit,
    val openProjectsFolder: () -> Unit,
    val currentPicoConfiguration: () -> PicoProjectConfiguration,
    val openFilePicker: () -> Unit,
    val openFile: (String) -> Unit,
    val navigateToFile: (String, Int, Int) -> Unit,
    val createGeneralProject: (String, GeneralProjectTemplate) -> Unit,
    val createFile: (String) -> Unit,
    val createFolder: (String) -> Unit,
    val renamePath: (String, String, Boolean) -> Unit,
    val movePath: (String, String, Boolean) -> Unit,
    val copyPath: (String, String, Boolean) -> Unit,
    val deletePath: (String, Boolean) -> Unit,
    val openPicoExtensionDetails: () -> Unit,
    val openCppExtensionDetails: () -> Unit,
    val openPythonExtensionDetails: () -> Unit,
    val openRustExtensionDetails: () -> Unit,
    val openGnuLanguagesExtensionDetails: () -> Unit,
    val openWebExtensionDetails: () -> Unit,
    val openGitExtensionDetails: () -> Unit,
    val openPicoHardwareApis: () -> Unit,
    val openPicoHighLevelApis: () -> Unit,
    val openPicoNetworkingLibraries: () -> Unit,
    val openPicoRuntimeInfrastructure: () -> Unit,
    val openPicoSdkReference: () -> Unit,
    val createPicoProject: (String, PicoBoard, PicoProjectLanguage) -> Unit,
    val createPicoExample: (String, PicoBoard, PicoExample, PicoProjectLanguage) -> Unit,
    val runPicoUsb: () -> Unit,
    val configurePicoProject: (PicoProjectConfiguration) -> Unit,
    val configurePicoCMake: () -> Unit,
    val cleanPicoBuild: () -> Unit,
    val runGitOperation: (() -> GitRepositoryState) -> Unit,
    val runGitProjectOperation: (Boolean, ActivityDestination, () -> GitProjectResult) -> Unit,
    val sendConsoleInput: (String) -> Unit,
    val requestSemanticCompletion: (String, String, Int) -> Unit,
    val requestSemanticDiagnostics: (String, String) -> Unit,
)
