package dev.foldcode.ide

import android.content.Context
import org.json.JSONArray
import java.io.Closeable
import java.io.File
import java.util.concurrent.Executors
import java.util.concurrent.TimeUnit
import java.util.concurrent.atomic.AtomicLong
import java.util.concurrent.atomic.AtomicReference

internal fun isAssemblySource(path: String): Boolean =
    path.substringAfterLast('.', "").lowercase() in setOf("s", "asm")

/** ARM/RISC-V completion using the board selected by the Pico project. */
internal fun assemblyCompletionItems(projectSources: Map<String, String>): List<CompletionItem> {
    val common = assemblyDirectives + assemblyCommonInstructions
    if (projectSources.isEmpty()) return common
    val architecture = if (picoBoard(projectSources).chip == PicoChip.Rp2350RiscV) {
        riscvAssemblyItems
    } else {
        armAssemblyItems
    }
    val labels = projectSources
        .filterKeys(::isAssemblySource)
        .values
        .asSequence()
        .flatMap { source ->
            Regex("(?m)^\\s*([A-Za-z_.$][A-Za-z0-9_.$]*):").findAll(source).map { it.groupValues[1] }
        }
        .distinct()
        .map { CompletionItem(it, it, "Project assembly label") }
        .toList()
    return (labels + architecture + common).distinctBy { it.label.lowercase() }
}

private fun assemblyWords(words: String, detail: String): List<CompletionItem> =
    words.split(Regex("\\s+")).filter(String::isNotBlank).map { CompletionItem(it, it, detail) }

private val assemblyDirectives = listOf(
    CompletionItem("section", "section ", "GNU assembler directive · .section"),
    CompletionItem("text", "text", "GNU assembler directive · .text"),
    CompletionItem("data", "data", "GNU assembler directive · .data"),
    CompletionItem("global", "global ", "GNU assembler directive · .global"),
    CompletionItem("type", "type ", "GNU assembler directive · .type"),
    CompletionItem("size", "size ", "GNU assembler directive · .size"),
    CompletionItem("align", "align ", "GNU assembler directive · .align"),
    CompletionItem("word", "word ", "GNU assembler directive · .word"),
    CompletionItem("byte", "byte ", "GNU assembler directive · .byte"),
    CompletionItem("macro", "macro ", "GNU assembler directive · .macro"),
    CompletionItem("endm", "endm", "GNU assembler directive · .endm"),
)

private val assemblyCommonInstructions = assemblyWords(
    "nop b call ret push pop",
    "Assembly instruction",
)
private val armAssemblyItems =
    assemblyWords(
        "mov movs mvn add adds adc sub subs sbc mul and ands orr eor bic lsl lsr asr ror cmp cmn tst " +
            "ldr ldrb ldrh ldrsb ldrsh str strb strh bl blx bx beq bne bcs bcc bmi bpl bhi bls bge blt bgt ble " +
            "cbz cbnz wfi wfe sev dmb dsb isb svc bkpt",
        "ARM Thumb instruction",
    ) + assemblyWords(
        "r0 r1 r2 r3 r4 r5 r6 r7 r8 r9 r10 r11 r12 sp lr pc",
        "ARM register",
    )
private val riscvAssemblyItems =
    assemblyWords(
        "li la mv neg not add addi sub sll slli slt slti sltu sltiu xor xori srl srli sra srai or ori and andi " +
            "lui auipc lb lh lw lbu lhu sb sh sw jal jalr beq bne blt bge bltu bgeu tail ecall ebreak fence " +
            "csrr csrw csrrw csrrs csrrc",
        "RISC-V instruction",
    ) + assemblyWords(
        "zero ra sp gp tp t0 t1 t2 t3 t4 t5 t6 s0 s1 s2 s3 s4 s5 s6 s7 s8 s9 s10 s11 a0 a1 a2 a3 a4 a5 a6 a7",
        "RISC-V register",
    )

/**
 * Assembles an unsaved mirror with the exact command generated by Pico CMake.
 * This provides target-correct diagnostics without modifying the real project.
 */
internal class AssemblyIntelligence(context: Context) : Closeable {
    private val appContext = context.applicationContext
    private val toolchain = BundledToolchain(appContext)
    private val executor = Executors.newSingleThreadExecutor { runnable ->
        Thread(runnable, "FoldCode-assembly-intelligence").apply { isDaemon = true }
    }
    private val generation = AtomicLong(0)
    private val activeProcess = AtomicReference<Process?>(null)
    @Volatile private var lastKey: String? = null
    @Volatile private var lastDiagnostics: List<CodeDiagnostic> = emptyList()

    fun requestDiagnostics(
        project: File,
        relativeFile: String,
        source: String,
        callback: (List<CodeDiagnostic>) -> Unit,
    ) {
        val key = "${project.absolutePath}\u0000$relativeFile\u0000${source.hashCode()}\u0000${source.length}"
        if (lastKey == key) {
            callback(lastDiagnostics)
            return
        }
        val ticket = generation.incrementAndGet()
        activeProcess.getAndSet(null)?.terminateTree()
        executor.execute {
            if (ticket != generation.get()) return@execute
            val result = runCatching { diagnose(project, relativeFile, source, ticket) }.getOrDefault(emptyList())
            if (ticket == generation.get()) {
                lastKey = key
                lastDiagnostics = result
                callback(result)
            }
        }
    }

    fun reset() {
        generation.incrementAndGet()
        activeProcess.getAndSet(null)?.terminateTree()
        lastKey = null
        lastDiagnostics = emptyList()
    }

    override fun close() {
        reset()
        executor.shutdownNow()
    }

    private fun diagnose(project: File, relativeFile: String, source: String, ticket: Long): List<CodeDiagnostic> {
        if (!isAssemblySource(relativeFile) || !project.isDirectory) return emptyList()
        toolchain.install()
        val root = project.canonicalFile
        val realSource = File(root, relativeFile).canonicalFile
        require(realSource.toPath().startsWith(root.toPath())) { "Assembly source is outside the project" }
        val invocation = assemblyCompileCommand(root, realSource) ?: return emptyList()
        val mirrorRoot = File(
            appContext.cacheDir,
            "assembly-diagnostics/${root.absolutePath.hashCode().toUInt().toString(16)}",
        )
        val mirrorSource = File(mirrorRoot, relativeFile).canonicalFile
        require(mirrorSource.toPath().startsWith(mirrorRoot.canonicalFile.toPath())) { "Invalid assembly path" }
        mirrorSource.parentFile?.mkdirs()
        mirrorSource.writeText(if (source.endsWith('\n')) source else "$source\n")
        val objectFile = File(mirrorRoot, ".diagnostic.o").apply { delete() }
        val configuredCompiler = File(invocation.arguments.first())
        val clangDriver = runCatching {
            configuredCompiler.canonicalFile == toolchain.clang.canonicalFile
        }.getOrDefault(false)
        val command = sanitizeAssemblyCommand(invocation.arguments, invocation.directory, realSource) + listOf(
            if (clangDriver) "-fno-color-diagnostics" else "-fdiagnostics-color=never",
            "-I${realSource.parentFile?.absolutePath ?: root.absolutePath}",
            "-c", mirrorSource.absolutePath,
            "-o", objectFile.absolutePath,
        )
        if (ticket != generation.get()) return emptyList()
        val outputFile = File(mirrorRoot, ".diagnostic.log").apply { delete() }
        val process = ProcessBuilder(command)
            .directory(invocation.directory)
            .redirectErrorStream(true)
            .redirectOutput(outputFile)
            .apply {
                environment()["HOME"] = appContext.filesDir.absolutePath
                environment()["TMPDIR"] = appContext.cacheDir.absolutePath
                environment()["LD_LIBRARY_PATH"] =
                    "${toolchain.nativeDependencies.absolutePath}:${appContext.applicationInfo.nativeLibraryDir}"
                environment()["FOLDCODE_LLD_CORE"] =
                    File(toolchain.nativeDependencies, "libfoldlldcore.so").absolutePath
                File(appContext.filesDir, "gnu-arm-runtime").takeIf(File::isDirectory)?.let {
                    environment()["FOLDCODE_GNU_ARM_ROOT"] = it.absolutePath
                }
            }
            .start()
        activeProcess.set(process)
        return try {
            if (!process.waitFor(12, TimeUnit.SECONDS)) process.terminateTree()
            if (ticket != generation.get()) emptyList()
            else parseDiagnostics(outputFile.takeIf(File::isFile)?.readText().orEmpty())
        } finally {
            activeProcess.compareAndSet(process, null)
            objectFile.delete()
            outputFile.delete()
        }
    }

    private fun assemblyCompileCommand(project: File, source: File): CompileInvocation? {
        val database = File(project, "build/compile_commands.json").takeIf(File::isFile) ?: return null
        val entries = JSONArray(database.readText())
        for (index in 0 until entries.length()) {
            val entry = entries.getJSONObject(index)
            val directory = File(entry.optString("directory", project.absolutePath)).canonicalFile
            val listed = File(entry.optString("file"))
            val resolved = (if (listed.isAbsolute) listed else File(directory, listed.path)).canonicalFile
            if (resolved != source) continue
            val jsonArguments = entry.optJSONArray("arguments")
            val arguments = if (jsonArguments != null) {
                (0 until jsonArguments.length()).map(jsonArguments::getString)
            } else {
                assemblyShellWords(entry.getString("command"))
            }
            if (arguments.isNotEmpty()) return CompileInvocation(arguments, directory)
        }
        return null
    }

    private fun sanitizeAssemblyCommand(command: List<String>, directory: File, source: File): List<String> {
        val result = mutableListOf<String>()
        var skipNext = false
        command.forEachIndexed { index, argument ->
            if (skipNext) {
                skipNext = false
                return@forEachIndexed
            }
            if (index == 0) {
                val configured = File(argument)
                result += if (configured.canExecute()) configured.absolutePath else toolchain.clang.absolutePath
                return@forEachIndexed
            }
            if (argument in setOf("-o", "-MF", "-MT", "-MQ", "--serialize-diagnostics")) {
                skipNext = true
                return@forEachIndexed
            }
            if (argument == "-c" || argument in setOf("-MMD", "-MD", "-MP")) return@forEachIndexed
            if (argument.startsWith("-o") || argument.startsWith("-MF") ||
                argument.startsWith("-MT") || argument.startsWith("-MQ")
            ) return@forEachIndexed
            val candidate = if (File(argument).isAbsolute) File(argument) else File(directory, argument)
            if (runCatching { candidate.canonicalFile == source }.getOrDefault(false)) return@forEachIndexed
            result += argument
        }
        return result
    }

    private data class CompileInvocation(val arguments: List<String>, val directory: File)
}

private fun assemblyShellWords(command: String): List<String> {
    val words = mutableListOf<String>()
    val current = StringBuilder()
    var quote: Char? = null
    var escaped = false
    command.forEach { char ->
        when {
            escaped -> { current.append(char); escaped = false }
            char == '\\' && quote != '\'' -> escaped = true
            quote != null && char == quote -> quote = null
            quote == null && (char == '\'' || char == '"') -> quote = char
            quote == null && char.isWhitespace() -> if (current.isNotEmpty()) {
                words += current.toString()
                current.clear()
            }
            else -> current.append(char)
        }
    }
    if (escaped) current.append('\\')
    if (current.isNotEmpty()) words += current.toString()
    return words
}
