# Portable Raspberry Pi Pico SDK import helper generated by FoldCode.
# Include this file before project() in CMakeLists.txt.

if(DEFINED ENV{PICO_SDK_PATH} AND NOT PICO_SDK_PATH)
    set(PICO_SDK_PATH $ENV{PICO_SDK_PATH})
endif()

if(DEFINED ENV{PICO_SDK_FETCH_FROM_GIT} AND NOT PICO_SDK_FETCH_FROM_GIT)
    set(PICO_SDK_FETCH_FROM_GIT $ENV{PICO_SDK_FETCH_FROM_GIT})
endif()

if(DEFINED ENV{PICO_SDK_FETCH_FROM_GIT_TAG} AND NOT PICO_SDK_FETCH_FROM_GIT_TAG)
    set(PICO_SDK_FETCH_FROM_GIT_TAG $ENV{PICO_SDK_FETCH_FROM_GIT_TAG})
endif()

set(PICO_SDK_PATH "${PICO_SDK_PATH}" CACHE PATH "Path to the Raspberry Pi Pico SDK")
set(PICO_SDK_FETCH_FROM_GIT "${PICO_SDK_FETCH_FROM_GIT}" CACHE BOOL "Fetch the Pico SDK when no local SDK is configured")
set(PICO_SDK_FETCH_FROM_GIT_TAG "${PICO_SDK_FETCH_FROM_GIT_TAG}" CACHE STRING "Pico SDK Git tag")

if(NOT PICO_SDK_PATH)
    if(PICO_SDK_FETCH_FROM_GIT)
        include(FetchContent)
        if(NOT PICO_SDK_FETCH_FROM_GIT_TAG)
            set(PICO_SDK_FETCH_FROM_GIT_TAG "2.3.0")
        endif()
        FetchContent_Declare(
            pico_sdk
            GIT_REPOSITORY https://github.com/raspberrypi/pico-sdk
            GIT_TAG ${PICO_SDK_FETCH_FROM_GIT_TAG}
            GIT_SUBMODULES_RECURSE FALSE
        )
        FetchContent_GetProperties(pico_sdk)
        if(NOT pico_sdk_POPULATED)
            FetchContent_Populate(pico_sdk)
        endif()
        set(PICO_SDK_PATH ${pico_sdk_SOURCE_DIR})
    else()
        message(FATAL_ERROR "Set PICO_SDK_PATH or enable PICO_SDK_FETCH_FROM_GIT")
    endif()
endif()

get_filename_component(PICO_SDK_PATH "${PICO_SDK_PATH}" REALPATH BASE_DIR "${CMAKE_BINARY_DIR}")
set(PICO_SDK_INIT_CMAKE_FILE "${PICO_SDK_PATH}/pico_sdk_init.cmake")
if(NOT EXISTS "${PICO_SDK_INIT_CMAKE_FILE}")
    message(FATAL_ERROR "${PICO_SDK_PATH} does not contain the Raspberry Pi Pico SDK")
endif()

set(PICO_SDK_PATH "${PICO_SDK_PATH}" CACHE PATH "Path to the Raspberry Pi Pico SDK" FORCE)
include("${PICO_SDK_INIT_CMAKE_FILE}")
