package dev.foldcode.ide

import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertSame
import org.junit.Assert.assertTrue
import org.junit.Rule
import org.junit.Test
import org.junit.rules.TemporaryFolder
import java.io.File

class RustCargoCompatibilityTest {
    @get:Rule
    val temporary = TemporaryFolder()

    @Test
    fun generatedCargoLockIsRetainedByTheNextEditorSave() {
        val project = temporary.newFolder("generated-lock-project")
        val editorSources = linkedMapOf(
            "Cargo.toml" to "[package]\nname = \"firmware\"\nversion = \"0.1.0\"\n",
            "src/main.rs" to "fn main() {}\n",
        )
        File(project, "Cargo.lock").writeText("# generated by Cargo\nversion = 4\n")

        val sourcesToSave = rustProjectSourcesForSave(project, editorSources)

        assertEquals("# generated by Cargo\nversion = 4\n", sourcesToSave["Cargo.lock"])
        assertEquals(editorSources["src/main.rs"], sourcesToSave["src/main.rs"])
    }

    @Test
    fun editorCargoLockWinsAndMissingGeneratedLockDoesNotChangeTheSnapshot() {
        val project = temporary.newFolder("editor-lock-project")
        val editorSources = mapOf("Cargo.toml" to "[package]\nname = \"firmware\"\n")

        assertSame(editorSources, rustProjectSourcesForSave(project, editorSources))

        File(project, "Cargo.lock").writeText("disk lock\n")
        val editedLock = editorSources + ("Cargo.lock" to "editor lock\n")
        assertSame(editedLock, rustProjectSourcesForSave(project, editedLock))
    }

    @Test
    fun firstAnalysisFetchesPatchesAndMarksDependenciesThenStaysOffline() {
        val project = temporary.newFolder("rust-project")
        val targetDirectory = temporary.newFolder("rust-target")
        File(project, "Cargo.toml").writeText("[package]\nname = \"firmware\"\nversion = \"0.1.0\"\n")
        File(project, ".cargo").mkdirs()
        File(project, ".cargo/config.toml").writeText("[build]\ntarget = \"thumbv6m-none-eabi\"\n")
        var fetches = 0

        val prepared = prepareRustCargoCompatibility(
            project,
            "thumbv6m-none-eabi",
            targetDirectory,
            StringBuilder(),
            {},
        ) { arguments, _ ->
            fetches++
            assertEquals(listOf("fetch", "--target", "thumbv6m-none-eabi"), arguments)
            val source = File(
                project,
                ".foldcode/cargo/registry/src/index/proc-macro-error2-2.0.1/src/lib.rs",
            )
            source.parentFile?.mkdirs()
            source.writeText("extern crate proc_macro;\npub use proc_macro;\n")
            true
        }

        assertTrue(prepared)
        assertEquals(1, fetches)
        assertTrue(
            File(
                project,
                ".foldcode/cargo/registry/src/index/proc-macro-error2-2.0.1/src/lib.rs",
            ).readText().contains("pub extern crate proc_macro;"),
        )
        assertTrue(File(project, ".foldcode/compat/proc-macro-error2-2.0.1-rust-1.97-r2").isFile)
        assertTrue(File(project, ".foldcode/compat").listFiles().orEmpty().any {
            it.name.startsWith("cargo-dependencies-thumbv6m-none-eabi-")
        })

        assertTrue(
            prepareRustCargoCompatibility(
                project,
                "thumbv6m-none-eabi",
                targetDirectory,
                StringBuilder(),
                {},
            ) { _, _ ->
                fetches++
                false
            },
        )
        assertEquals("Prepared inputs must remain offline", 1, fetches)
    }

    @Test
    fun changingCargoInputsRefreshesDependencies() {
        val project = temporary.newFolder("changing-project")
        val targetDirectory = temporary.newFolder("changing-target")
        val manifest = File(project, "Cargo.toml")
        manifest.writeText("[dependencies]\nembedded-hal = \"1\"\n")
        var fetches = 0
        fun prepare(): Boolean = prepareRustCargoCompatibility(
            project,
            "thumbv8m.main-none-eabihf",
            targetDirectory,
            StringBuilder(),
            {},
        ) { _, _ ->
            fetches++
            true
        }

        assertTrue(prepare())
        assertEquals(1, fetches)
        manifest.appendText("panic-halt = \"0.2\"\n")
        assertTrue(prepare())
        assertEquals(2, fetches)
    }

    @Test
    fun failedDependencyFetchDoesNotCreateReadyMarker() {
        val project = temporary.newFolder("failed-project")
        val targetDirectory = temporary.newFolder("failed-target")
        File(project, "Cargo.toml").writeText("[dependencies]\nmissing = \"1\"\n")
        val output = StringBuilder()

        assertFalse(
            prepareRustCargoCompatibility(
                project,
                "riscv32imac-unknown-none-elf",
                targetDirectory,
                output,
                {},
            ) { _, consume ->
                consume("dependency download failed")
                false
            },
        )
        assertTrue(output.contains("dependency download failed"))
        assertFalse(File(project, ".foldcode/compat").listFiles().orEmpty().any {
            it.name.startsWith("cargo-dependencies-")
        })
    }
}
